services:
  - type: web
    name: curriculum-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://curriculum-tracker-frontend.onrender.com
      - key: RENDER_EXTERNAL_URL
        value: https://curriculum-tracker-backend.onrender.com

  - type: web
    name: curriculum-tracker-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run build && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://curriculum-tracker-backend.onrender.com 