services:
  - type: web
    name: curriculum-tracker-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_URL
        value: https://curriculum-tracker-frontend.onrender.com
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: web
    name: curriculum-tracker-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://curriculum-tracker-backend.onrender.com
      - key: NODE_VERSION
        value: 18.17.0 